2022-06-30 21:19:12,616 INFO    MainThread:29664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\DESKTOP\.config\wandb\settings
2022-06-30 21:19:12,616 INFO    MainThread:29664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\DESKTOP\Desktop\github repo\KDD_TACCO\wandb\settings
2022-06-30 21:19:12,616 INFO    MainThread:29664 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-30 21:19:12,616 INFO    MainThread:29664 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-30 21:19:12,616 INFO    MainThread:29664 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-30 21:19:12,617 INFO    MainThread:29664 [wandb_init.py:_log_setup():428] Logging user logs to C:\Users\DESKTOP\Desktop\github repo\KDD_TACCO\wandb\run-20220630_211912-s24cypeu\logs\debug.log
2022-06-30 21:19:12,617 INFO    MainThread:29664 [wandb_init.py:_log_setup():429] Logging internal logs to C:\Users\DESKTOP\Desktop\github repo\KDD_TACCO\wandb\run-20220630_211912-s24cypeu\logs\debug-internal.log
2022-06-30 21:19:12,618 INFO    MainThread:29664 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001F069D21508>
2022-06-30 21:19:12,618 INFO    MainThread:29664 [wandb_init.py:init():462] calling init triggers
2022-06-30 21:19:12,618 INFO    MainThread:29664 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-30 21:19:12,618 INFO    MainThread:29664 [wandb_init.py:init():515] starting backend
2022-06-30 21:19:12,618 INFO    MainThread:29664 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-06-30 21:19:12,624 INFO    MainThread:29664 [backend.py:ensure_launched():217] starting backend process...
2022-06-30 21:19:12,700 INFO    MainThread:29664 [backend.py:ensure_launched():222] started backend process with pid: 31392
2022-06-30 21:19:12,701 INFO    MainThread:29664 [wandb_init.py:init():525] backend started and connected
2022-06-30 21:19:12,716 INFO    MainThread:29664 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-06-30 21:19:12,718 INFO    MainThread:29664 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-06-30 21:19:12,718 INFO    MainThread:29664 [wandb_init.py:init():596] updated telemetry
2022-06-30 21:19:12,782 INFO    MainThread:29664 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-30 21:19:42,786 INFO    MainThread:29664 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-30 21:19:42,786 ERROR   MainThread:29664 [wandb_init.py:init():636] backend process timed out
2022-06-30 21:19:42,786 ERROR   MainThread:29664 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-30 21:19:42,796 ERROR   MainThread:29664 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\wandb_init.py", line 999, in init
    run = wi.init()
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\wandb_init.py", line 651, in init
    backend.cleanup()
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\backend\backend.py", line 246, in cleanup
    self.interface.join()
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 475, in join
    super().join()
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\interface\interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\DESKTOP\anaconda3\envs\a2\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
